Issue 5/add loading indicator
Packstack-Tech/app pull request #34
Opened 2024-01-07 16:50 UTC by NoahMLoomis

### Features
- Added a Loading Spinner that automatically centers vertically and horizontally based on size of parent components
- Replaced any instance of 'Loading...' text with the spinner

2024-01-07 19:14 UTC, maplethorpej requested changes
Thank you, this will be a great visual improvement. One code suggestion

2024-01-07 19:14 UTC, maplethorpej commented on src/components/ui/Loading.tsx
> +  }
What do you think about making this an object instead? Since we know a key will be provided...

```
const spinnerSize = { sm: 'w-8 h-8', md: 'w-12 h-12', lg: 'w-14 h-14' }
...
spinnerSize[size]
```

2024-01-07 19:43 UTC, NoahMLoomis commented on src/components/ui/Loading.tsx
> +  }
Good idea, I'll implement it

2024-01-08 02:10 UTC, maplethorpej approved these changes

2024-01-08 02:10 UTC, merged